### ISSUE TITLE
Identation not working properly

### ISSUE THREAD

**Issue by Oxey405** [tgrosinger/advanced-tables-obsidian#285] opened 2023-09-11 07:02 UTC
**Describe the bug**
In markdown, the length of a piece of text doesn't necessarily represent the size of the string displayed on screen.
For example, bold text (with \*\*) adds 4 characters to the length of the raw string. This makes identation when creating a table looks buggy and adds too much space.

**To Reproduce**
1. Open any obsidian file
2. Create a table
3. In one of the cells, put a bold or italic text or a link with a custom display text
4. Press "enter" to add a new column and auto-indent

**Expected behavior**
Identation should work using how much characters are produced after the markdown compiler and not from raw markdown.

**Screenshots**
(none to provide)

**Desktop (please complete the following information):**     
 - OS: [Windows 11
 - Obsidian 1.4.5
 - Advanced Tables Version: 0.19.1

**Additional context**

**Comment by berisap** [comment] 2023-11-17 08:16
I noticed the same issue see screenshot at the bottom, it would be really cool if the markdown styling symbols would be regardet for in the identation.

![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/72547870/471fa18e-9c8f-4853-badd-cef76c94c1ee)

```
| title                                                             |
| ----------------------------------------------------------------- |
| regular text                                                      |
| *italic text* notice bars are not aligned after pressing enter -> |
| regular text                                                      | 
```

**Comment by tgrosinger** [comment] 2023-11-17 15:36
Duplicate of #145

**Closed by tgrosinger** 2023-11-17 15:36 UTC
Labels: duplicate
