### ISSUE TITLE
Feature Request: Split Individual Cells

### ISSUE THREAD

**Issue by MTRG15** [tgrosinger/advanced-tables-obsidian#231] opened 2022-12-25 17:24 UTC
A very useful feature is the ability to split/merge a single cell into 2 or more cells, similar to MS Excel, LibreOffice and Google Sheets, like so

![image](https://user-images.githubusercontent.com/25782754/209476924-c388a9bf-e523-40c7-9cb4-f6cf43fe0e2b.png)

The representation of a split cell could theoretically use an additional symbol, for example

| Col1 |  Col 2                                | Col 3 |
| ----  | --------------------------    | ----- |
|  Normal cell             |    Normal cell                                      |    Normal cell           |
|   Normal cell            | **Split Cell**  ``` %\|%```   **Split Cell**  |   Normal cell            |
|   Normal cell            |  Normal cell                                              |   Normal cell            |

I assume doing this would prevent or make much more complex to export certain formats like csv (which is probably the reason this doesn't exist)

Perhaps this already exist? Or there is a workaround I don't know, comments are welocome

**Comment by khorton** [comment] 2022-12-25 18:38
Does Obsidian support tables with cells that span multiple rows?  If not, nothing can be done here until Obsidian supports such tables.

**Comment by MTRG15** [comment] 2022-12-25 23:51
Great question... following Markdown official syntax, that is not possible, although it is with HTML, but implementing that would be a whole new plug in I guess...

Thanks for clearing it out, perhaps this could become a new thing in the future

**Comment by khorton** [comment] 2022-12-26 01:29
This could perhaps be considered a duplicate of [Issue #20](https://github.com/tgrosinger/advanced-tables-obsidian/issues/20), but with the problem described in a different way.

**Closed** 2022-12-26 02:03 UTC
Labels: enhancement, needs-review
