### ISSUE TITLE
Links and footnotes within a table formats the table spacing in edit mode incorrectly

### ISSUE THREAD

**Issue by jakez** [tgrosinger/advanced-tables-obsidian#232] opened 2022-12-27 14:53 UTC
**Describe the bug**
When adding either an internal or external link within a table, the spacing is incorrectly calculated while editing.

**To Reproduce**
1. Create a table
2. In one of the cells, put an internal link to another page
3. In another cell, put an external link to a website
4. In yet another cell, put a reference to a footnote

**Expected behavior**
The columns to align correctly.

**Actual behavior**
The table columns become misaligned in edit mode, as the brackets `[[ ]]` or the external link text `[foo](http://bar.com)` or the footnote `[^1]` are not correctly factored in to create a correct alignment of the column pipes.

**Screenshots**
Please see the screenshots for examples of a 2-column table breaking in edit mode

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4934456/209683212-86516230-72a1-4275-ade4-6043190c7f84.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/4934456/209685476-8b1bb7fa-1e64-4e5a-8064-f8ca140f7747.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: v1.1.9 (installer v1.1.8)
 - Advanced Tables Version: v0.18.1

**Additional context**
Appreciate the plugin and all that you have done for the community. Thanks for your consideration!

**Comment by velvetsmog** [comment] 2022-12-27 14:57
This bug might be related to #202

**Comment by R3migz** [comment] 2022-12-29 15:40
Same issue with tags too

**Comment by robertandrews** [comment] 2023-01-07 23:28
Here is a simple wikilink (`[[00-09 Systems]]`) throwing it off.
![IMG_1107](https://user-images.githubusercontent.com/3158787/211173940-e6cd9417-9f29-48f0-a10c-f0fb900d16e6.jpeg)

**Comment by GatorHog** [comment] 2023-01-25 17:35
#202

**Comment by hilsonp** [comment] 2023-06-18 19:04
Could the MR be merged so we can keep the correct padding when simply adding links ?

**Comment by tgrosinger** [comment] 2023-07-15 04:11
Please see #1455. I believe this is a duplicate of that issue.

**Closed by tgrosinger** 2023-07-15 04:11 UTC
Labels: bug, needs-review
