### ISSUE TITLE
[Feature request] Finally supporting new line in a cell ?

### ISSUE THREAD

**Issue by Elaws** [tgrosinger/advanced-tables-obsidian#218] opened 2022-10-27 11:42 UTC
**Is your feature request related to a problem? Please describe.**

Typing / editing a long text inside a cell is a nightmare : are there any plans to finally support having several lines in a cell row ? 

I read a few months ago it was not possible, but this is really needed from UX standpoint.

Should we create a feature request for Obsidian ?

Thanks !

**Solution :**
We could use shift + enter to get a new line in a cell.

**Alternatives :**

Current workaround (using `<br>`) is cumbersome and do not alleviate the pain of editing a long text in a table.

**Comment by zapp42** [comment] 2022-10-31 15:17
Duplicate of #215.

**Comment by g1ronn1mo** [comment] 2022-11-07 18:45
I think Onenote deals with this, by only inserting the next cell downwards, if there is a newline in the previous cell:

| header1    | header2                            |
|------------|-----------------------------|
| some text | more text \n I<curser       |

After pressing enter, the curser moves to the next row

| header1    | header2                            |
|------------|-----------------------------|
| some text | more text                          |
| I<curser    | more text                         |

The same could be for tabs. So that the possibility is given to use tabs inside the cell. 

| header1    | header2                            |
|------------|-----------------------------|
| some text | more text \t I<curser       |

After pressing tab again create new column 

| header1    | header2                            |                  |
|------------|-----------------------------|-------------|
| some text | more text                         |  I<curser    |

**Comment by tgrosinger** [comment] 2022-11-26 21:56
This plugin is not able to add support for multiple lines within a table cell. That is a feature of the markdown syntax itself, not just the formatting and rendering. Sorry.

**Closed by tgrosinger** 2022-11-26 21:56 UTC
Labels: enhancement, needs-review

**Comment by tonyxiao** [comment] 2022-11-29 09:32
Typora has a really great implementation of this while still being a fully compliant markdown editor
