### ISSUE TITLE
Tab key creates an indentation instead of creating a table

### ISSUE THREAD

**Issue by ralphirri** [tgrosinger/advanced-tables-obsidian#263] opened 2023-05-29 14:44 UTC
I have Obsidian and the Advanced Tables plug-in both on their latest version.

When I try to create a table using the "|" key, when I press TAB to create a table, it instead creates an indentation for the text. Can someone help me with this?
[https://imgur.com/a/PCHubhW](url)

**Comment by tgrosinger** [comment] 2023-05-29 15:29
Hello, I think this is a duplicate of #256.

**Closed by tgrosinger** 2023-05-29 15:29 UTC
