### ISSUE TITLE
Cell merging

### ISSUE THREAD

**Issue by Scarlov** [tgrosinger/advanced-tables-obsidian#80] opened 2021-04-19 08:20 UTC
**Is your feature request related to a problem? Please describe.**
I don't know if it's possible in Markdown, I know you can do it in HTML. What I would like to see is the ability to combine and merge cells vertically and horizontally. 
![image](https://user-images.githubusercontent.com/72456958/115202811-b25c8300-a0ee-11eb-8aa4-4b659695b82a.png)`

**Describe the solution you'd like**
A syntax that would indicate cell merging:
- for horizontal cell merging deletion of the " | " symbol might result in cells merging
- for vertical the top cell could look like this " |< (cell contents) | " and the bottom one like this " | (cell contents) >| " . `The` table above could be written like this:
```markdown
| Layer 1 | Layer 2 | Layer 3 |
| ------- | ------- | ------- |
|<        |< L2     |         |
| L1 Name | Name A >|         |
|         |< L2     |         |
|        >| Name B >|         |

```

**Describe alternatives you've considered**

**Additional context**
I love your plugin, it is definitely one of my favourites. If the feature is to hard to implement then my apologies for being unreasonable 😅.

**Comment by tgrosinger** [comment] 2021-04-19 14:23
@Scarlov, this question is a duplicate of #59. Please check out that issue for more details.

**Closed by tgrosinger** 2021-04-19 14:23 UTC
Labels: enhancement, needs-review
