### ISSUE TITLE
Do not create tables in code blocks

### ISSUE THREAD

**Issue by iampeternguyen** [tgrosinger/advanced-tables-obsidian#125] opened 2021-11-07 11:26 UTC
**Describe the bug**
Love the plug-in but it also auto creates tables in code blocks. I was writing out some code that included pipe operators `|`, and it kept creating tables.

**To Reproduce**
1. Create code block
2. add pipe operator

**Expected behavior**
It'd be nice if this plugin would ignore anything in code blocks.

**Comment by tgrosinger** [comment] 2021-11-25 04:44
Definitely agree, thank you for the bug report. I'll look into how I can detect that and prevent it.

**Comment by tgrosinger** [comment] 2021-11-26 00:54
Duplicate of #130

**Closed by tgrosinger** 2021-11-26 00:54 UTC
Labels: bug, duplicate
