### ISSUE TITLE
Strange x.y00000000000002 result with simple sum formula

### ISSUE THREAD

**Issue by arminus** [tgrosinger/advanced-tables-obsidian#220] opened 2022-11-01 13:25 UTC
**Describe the bug**
![2022-11-01_142051](https://user-images.githubusercontent.com/683680/199242979-7c4702ec-cc9f-40e0-8ad4-198217dfc5ba.png)

**To Reproduce**
As shown above, nothing special as far as I can tell.

**Expected behavior**
8.9 instead of 8.900000000000002 as result

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Win10
 - Obsidian Version: 1.0.3
 - Advanced Tables Version: 0.17.3

**Comment by cappslock** [comment] 2022-12-13 16:13
Most likely a limitation of floats, see: https://0.30000000000000004.com/

Could swap in a library like https://github.com/MikeMcl/decimal.js/ or https://github.com/MikeMcl/big.js/ on the various algebraic functions here: https://github.com/tgrosinger/md-advanced-tables/blob/main/src/calc/algebraic_operation.ts

**Comment by tgrosinger** [comment] 2023-05-25 15:16
I believe this is a duplicate of https://github.com/tgrosinger/md-advanced-tables/issues/46
Thank you.

**Closed by tgrosinger** 2023-05-25 15:16 UTC
Labels: bug, needs-review
