### ISSUE TITLE
Bolding in Live Preview doesn't align

### ISSUE THREAD

**Issue by Caddickbrown** [tgrosinger/advanced-tables-obsidian#157] opened 2022-01-14 13:26 UTC
**Describe the bug**
When bolding in Live Preview, the table stops aligning properly as the bold text removes the asterisk

**To Reproduce**
Bold something in a table while in Live Preview

**Expected behavior**
Table aligns as normal

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.13.19
 - Advanced Tables Version: 0.15.0

**Comment by tgrosinger** [comment] 2022-01-14 15:20
Duplicate of #145

**Closed by tgrosinger** 2022-01-14 15:20 UTC
Labels: bug, needs-review
